# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - nightly
notifications:
  email: false

matrix:
 allow_failures:
 - julia: 0.7
 - julia: nightly

after_success:
  # push coverage results to Coveralls and Codecov
  - julia -e 'cd(Pkg.dir("TensorOperations")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder());'
